### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by keenam** [synapticism/pendrell#1]
Hello,
When installing the theme I get the following error:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN gulp-jshint@2.0.0 requires a peer of jshint@2.x but none was installed.
npm ERR! Linux 3.10.0-327.4.5.el7.x86_64
npm ERR! argv "/home/rauers/usr/bin/node" "/home/rauers/usr/bin/npm" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! pendrell@0.46.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pendrell@0.46.0 postinstall script 'bower install'.

And when I run `bower install` separately, the following error is presented:

bower parse-srcset#*        not-cached https://github.com/albell/parse-srcset.git#*
bower parse-srcset#*           resolve https://github.com/albell/parse-srcset.git#*
bower open-iconic#^1.1.1    not-cached git://github.com/iconic/open-iconic.git#^1.1.1
bower open-iconic#^1.1.1       resolve git://github.com/iconic/open-iconic.git#^1.1.1
bower font-awesome-svg-png#^1.1.2       not-cached git://github.com/encharm/Font-Awesome-SVG-PNG.git#^1.1.2
bower font-awesome-svg-png#^1.1.2          resolve git://github.com/encharm/Font-Awesome-SVG-PNG.git#^1.1.2
bower ionicons#^2.0.1                   not-cached git://github.com/driftyco/ionicons.git#^2.0.1
bower ionicons#^2.0.1                      resolve git://github.com/driftyco/ionicons.git#^2.0.1
bower typicons#^2.0.7                   not-cached git://github.com/stephenhutchings/typicons.font.git#^2.0.7
bower typicons#^2.0.7                      resolve git://github.com/stephenhutchings/typicons.font.git#^2.0.7
bower open-iconic#^1.1.1                  download https://github.com/iconic/open-iconic/archive/1.1.1.tar.gz
bower font-awesome-svg-png#^1.1.2         download https://github.com/encharm/Font-Awesome-SVG-PNG/archive/1.1.2.tar.gz
bower typicons#^2.0.7                     download https://github.com/stephenhutchings/typicons.font/archive/2.0.7.tar.gz
bower ionicons#^2.0.1                     download https://github.com/driftyco/ionicons/archive/v2.0.1.tar.gz
bower ionicons#^2.0.1                      extract archive.tar.gz
bower open-iconic#^1.1.1                   extract archive.tar.gz
bower typicons#^2.0.7                      extract archive.tar.gz
bower ionicons#^2.0.1                     mismatch Version declared in the json (2.0.0) is different than the resolved one (2.0.1)
bower ionicons#^2.0.1                     resolved git://github.com/driftyco/ionicons.git#2.0.1
bower typicons#^2.0.7                     resolved git://github.com/stephenhutchings/typicons.font.git#2.0.7
bower font-awesome-svg-png#^1.1.2          extract archive.tar.gz
bower open-iconic#^1.1.1                  resolved git://github.com/iconic/open-iconic.git#1.1.1
bower font-awesome-svg-png#^1.1.2         resolved git://github.com/encharm/Font-Awesome-SVG-PNG.git#1.1.2
bower parse-srcset#*                       ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/albell/parse-srcset.git", exit code of #128

**Comment by synapticism** [comment]
First of all, I wouldn't use this theme as-is. I haven't really set it up for others to puzzle out.

Secondly, I checked into this with Bower v1.6.5 and v1.7.7 and it worked fine on both after clearing `bower_components` so I'm not too sure what might be wrong on your end. Let me know if you clear it up.
